# .gitlab-ci.yml
variables:
  PLUGINS_FILE: plugins.txt
image: alpine:latest
stages:
  - build
  - deploy

build_job:
  stage: build
  script:
    # Read plugins from file and store in variable
    - PLUGINS=$(cat $PLUGINS_FILE)
    # Use the plugins in your build process
    - |
      echo "Installing plugins: $PLUGINS"
    - |
      for plugin in $PLUGINS; do
        echo "Installing plugin: $plugin"
        # Add your plugin installation command here
        # For example: npm install $plugin
      done
  artifacts:
    paths:
      - $PLUGINS_FILE
    expire_in: 1 week

deploy_job:
  stage: deploy
  script:
    - echo "Deploying with plugins from $PLUGINS_FILE"
    - PLUGINS=$(cat $PLUGINS_FILE)
    # Use plugins in deployment if needed
  dependencies:
    - build_job